import React, { lazy } from 'react';

export const COMPONENT_REGISTRY: Record<string, any> = {
  "App": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/App.tsx').then(m => ({ default: m["App"] || m.default }))),
  "TestButton": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/TestButton.tsx').then(m => ({ default: m["TestButton"] || m.default }))),
  "getFrameworkPatterns": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/core/patterns.ts').then(m => ({ default: m["getFrameworkPatterns"] || m.default }))),
  "scanForComponents": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/core/scanner.ts').then(m => ({ default: m["scanForComponents"] || m.default }))),
  "watch": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/core/watcher.ts').then(m => ({ default: m["watch"] || m.default }))),
  "buildProjectGraph": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/scripts/dependency-mapper.ts').then(m => ({ default: m["buildProjectGraph"] || m.default }))),
  "generateMermaid": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/scripts/visualizer.ts').then(m => ({ default: m["generateMermaid"] || m.default }))),
  "parseComponent": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/assets/Parser.tsx').then(m => ({ default: m["parseComponent"] || m.default }))),
  "SuperButton": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/assets/TestComponent.tsx').then(m => ({ default: m["SuperButton"] || m.default }))),
  "CodeExamples": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/components/CodeExamples.tsx').then(m => ({ default: m["CodeExamples"] || m.default }))),
  "ComponentHeader": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/components/ComponentHeader.tsx').then(m => ({ default: m["ComponentHeader"] || m.default }))),
  "ComponentLivePreview": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/components/ComponentLivePreview.tsx').then(m => ({ default: m["ComponentLivePreview"] || m.default }))),
  "CoolSlider": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/components/CoolSlider.tsx').then(m => ({ default: m["CoolSlider"] || m.default }))),
  "PropsTable": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/components/PropsTable.tsx').then(m => ({ default: m["PropsTable"] || m.default }))),
  "SourceCodeViewer": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/components/SourceCodeViewer.tsx').then(m => ({ default: m["SourceCodeViewer"] || m.default }))),
  "getScopeForComponent": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/components/componentRegistry.ts').then(m => ({ default: m["getScopeForComponent"] || m.default }))),
  "Dashboard": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/dashboard-etc/Dashboard.tsx').then(m => ({ default: m["Dashboard"] || m.default }))),
  "PlayGround": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/dashboard-etc/PlayGround.tsx').then(m => ({ default: m["PlayGround"] || m.default }))),
  "SearchBar": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/dashboard-etc/SearchBar.tsx').then(m => ({ default: m["SearchBar"] || m.default }))),
  "SideBar": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/client/src/dashboard-etc/SideBar.tsx').then(m => ({ default: m["SideBar"] || m.default }))),
  "analyzeCommand": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/cli/commands/analyze.ts').then(m => ({ default: m["analyzeCommand"] || m.default }))),
  "generateCommand": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/cli/commands/generate.ts').then(m => ({ default: m["generateCommand"] || m.default }))),
  "scanCommand": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/cli/commands/scan.ts').then(m => ({ default: m["scanCommand"] || m.default }))),
  "serveCommand": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/cli/commands/serve.ts').then(m => ({ default: m["serveCommand"] || m.default }))),
  "watchCommand": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/cli/commands/watch.ts').then(m => ({ default: m["watchCommand"] || m.default }))),
  "Button": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/test/fixtures/Button.tsx').then(m => ({ default: m["Button"] || m.default }))),
  "Card": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/test/fixtures/Card.tsx').then(m => ({ default: m["Card"] || m.default }))),
  "Dropdown": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/test/fixtures/Dropdown.tsx').then(m => ({ default: m["Dropdown"] || m.default }))),
  "Input": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/test/fixtures/Input.tsx').then(m => ({ default: m["Input"] || m.default }))),
  "Modal": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/test/fixtures/Modal.tsx').then(m => ({ default: m["Modal"] || m.default }))),
  "UserProfile": lazy(() => import('/Users/dylpang/Desktop/Codesmith/OSP/PatternBook/PatternBook/services/test/fixtures/UserProfile.tsx').then(m => ({ default: m["UserProfile"] || m.default }))),
};
